engines:
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
ratings:
  paths:
  - "**.md"
  - "**.js"
